#!/bin/bash
#SBATCH --job-name=convert_v3_v2
#SBATCH --output=/home/lfeng/task_logs/%j.log
#SBATCH --partition=h100
#SBATCH --qos=vita
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=16
#SBATCH --gpus-per-node=1
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mem=50G

# Ensure logs directory exists
mkdir -p logs

# Set the repository ID and local root path
# Change these values as needed
REPO_ID="nvidia/PhysicalAI-Robotics-GR00T-Teleop-GR1"
ROOT_PATH="/work/vita/lanfeng/vlas/wise_dataset_0.4.3"

echo "Starting conversion for repo: $REPO_ID"
echo "Local root: $ROOT_PATH"

python scripts/lerobot_conversion/convert_v3_to_v2.py \
    --repo-id="merged_train" \
    --root "$ROOT_PATH"

echo "Conversion finished."
